name: test workflow

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: test ubuntu
    - run: date
  windows:
    runs-on: windows-latest
    steps:
    - name: test windows
    - run: date
